version: '3.8'

services:
  nextjs:
    container_name: bykov-attorney-nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network
  
  nginx:
    container_name: bykov-attorney-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./nginx/www:/var/www/html
    depends_on:
      - nextjs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
